namespace SpriteKind {
    export const TRASH = SpriteKind.create()
}
info.onLifeZero(function () {
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.TRASH, function (sprite, otherSprite) {
    EZEL_LGM += 1
    info.changeScoreBy(1)
    yadno_hyt()
    info.startCountdown(7)
    if (EZEL_LGM == 10) {
        EZEL_LGM = 0
        info.changeLifeBy(1)
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mulai == 1) {
        mulai = 0
        GW()
    }
})
function GW () {
    Jumla = 0
    tiles.setCurrentTilemap(tilemap`level1`)
    kim = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    light.showAnimation(light.runningLightsAnimation, 100)
    animation.runImageAnimation(
    kim,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    500,
    true
    )
    info.setLife(3)
    controller.moveSprite(kim)
    noel_gy = sprites.create(img`
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ..................................................bbbb..............................................
        .................................................bbfffbbb...........................................
        ..........................................bbbbbbbbffffffbb..........................................
        .........................................bbffffffffffffffbb.........................................
        .........................................bffffffffffffffffb.........................................
        .........................................bffffffffffffffffb.........................................
        .........................................bbfffffffffffffffb.........................................
        ..........................................bfffffffffffffffb.........................................
        ..........................................bfffffffffffffbfb.........................................
        ..........................................bffffffffffffbffb.........................................
        ..........................................bbbbffffffffbfffb.........................................
        .........................................bfffbffffffffbfffb.........................................
        .......................................bbffffbbfffffffbfffb.........................................
        .....................................bbfffffffbffffffbffffbb........................................
        .....................................bfffffffbbffffffbfffffbb.......................................
        ....................................bffffffffbbbffffbfffffffbbbbbbb.................................
        ...................................bfffffffbbfffffffbfffffffffffffbbbbbb............................
        ...................................bffffffbfffffffffffffbfffffffffffffffbbb.........................
        ...................................bfffffbfffffffffffffbfffffffffffffffffffb........................
        ...................................bffffbfffffffffffffbbfffffffffffffffffffb........................
        ..................................bffffffbffffffffffffbffffffffffffffffffffb........................
        .................................bfffffffbbfffffffffffbffffffffffffffffffffb........................
        ................................bfffffffffbbffffffffffbbffffbbbbbbbbfffffffb........................
        ................................bffffffffffbfffffffffbbffffffffffffbfffffffb........................
        ...............................bfffffffffffbfffffffffffffffffffffffbfffffffb........................
        ..............................bffffffffffffbffffffffffffffffffffffffbffffffb........................
        ..............................bffffffffffffbfffffffffffffffffffffffffffffffb........................
        ..............................bfffffffffffbffffffffffffffffffffffffffffffffb........................
        ..............................bfffffffffffbbbbbbbfffffffffbbfffffffffffffffb........................
        .............................bffffffffffffffffffffffffffffffbffffffffffffffb........................
        .............................bffffffffffffffffffffffffffffffbfffffffffffffb.........................
        ............................bffffbffffffffffffffffffffffffffbfffffffffffffb.........................
        ...........................bfffffbffffffffffffffffffffffffffbffffffffffffb..........................
        ..........................bbfffffbffffffffffffffffffffffffffbffffffffffffb..........................
        ..........................bffffffbffffffffffffffffffffffffffbfffffffffffb...........................
        ..........................bffffffbffffffffffffffbffffffffffbbfffffffffffb...........................
        .........................bfffffffbffffffffffffffbbffffffffbbfffffffffffb............................
        .........................bfffffffbffffbfffffffffffbfffffffffffffffffffb.............................
        .........................bfffffffbfffffbffffffffffbffffffffffffffffffb..............................
        .........................bffffffffbbffffbbffffffffbbffffffffffffffffbb..............................
        .........................bffffffffffffffffbbbffffffbbbbbfffffffffffb................................
        .........................bffffffffffffffffffbffffffffffbfffffffffffb................................
        .........................bffffffffffffffffffbffffffffffbffffffffffb.................................
        .........................bffffffffffffffffffbbfffffffffbfffffffffb..................................
        .........................bfffffffffffffffffffbbfffbbfffbfffffffffb..................................
        ..........................bbbffffffffffffffffffbbbbffffbfffffffffb..................................
        .............................bbffffffffffffffffffffffffbbfffffffbb..................................
        ...............................bbfffffffffffffffffffffffffffffffb...................................
        .................................bbfffffffffffffffffffffffffffffb...................................
        ...................................bbfffffffffffffffffffffffffffb...................................
        .....................................bffffffffffffffffffffffffffb...................................
        ......................................bbbbffffffffffffffffffffffb...................................
        ..........................................bfffffffffffffffffffffb...................................
        ..........................................bfffffffffffffffffffbb....................................
        ...........................................bffffffffffffffbbbb......................................
        ............................................bbffffffffffbb..........................................
        .............................................bbbbfbbbbbbb...........................................
        .................................................b..................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        `, SpriteKind.TRASH)
    scaling.scaleToPixels(noel_gy, 32, ScaleDirection.Horizontally, ScaleAnchor.Middle, true)
}
info.onCountdownEnd(function () {
    game.gameOver(false)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
function yadno_hyt () {
    austin_ire = randint(0, 7)
    if (austin_ire == 0) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tilePath5)
    } else if (austin_ire == 1) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tileGrass2)
    } else if (austin_ire == 2) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tilePath4)
    } else if (austin_ire == 3) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tilePath2)
    } else if (austin_ire == 4) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tilePath8)
    } else if (austin_ire == 5) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tilePath3)
    } else if (austin_ire == 6) {
        tiles.placeOnRandomTile(noel_gy, sprites.castle.tilePath6)
    }
}
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    if (Sbar_dulu_stephen == 0) {
        Sbar_dulu_stephen = 1
        info.changeLifeBy(-1)
        timer.after(1000, function () {
            Sbar_dulu_stephen = 0
        })
    }
})
let Ka_artur: Sprite = null
let Sbar_dulu_stephen = 0
let austin_ire = 0
let noel_gy: Sprite = null
let kim: Sprite = null
let Jumla = 0
let EZEL_LGM = 0
let mulai = 0
music.play(music.createSong(assets.song`BRR`), music.PlaybackMode.LoopingInBackground)
mulai = 1
info.setScore(0)
EZEL_LGM = 0
scene.setBackgroundImage(assets.image`scene1`)
game.onUpdateInterval(100, function () {
    scene.cameraFollowSprite(kim)
})
game.onUpdateInterval(1500, function () {
    if (mulai == 1) {
        scene.setBackgroundImage(assets.image`scene1`)
        timer.after(500, function () {
            scene.setBackgroundImage(assets.image`scene3`)
            timer.after(500, function () {
                scene.setBackgroundImage(assets.image`scene4`)
            })
        })
    }
})
forever(function () {
    if (mulai == 0) {
        tiles.setCurrentTilemap(tilemap`level1`)
    }
})
forever(function () {
    if (Jumla == 0) {
        if (info.score() == 10) {
            Jumla = 1
            Ka_artur = sprites.create(img`
                . . . . f f f f . . . . 
                . . f f d d d d f f . . 
                . f f d d d d d d f f . 
                f f f f b d d d f f f f 
                f f f b b b d d f f f f 
                f f f b b b b d d f f f 
                f b e 2 b b b b 2 e b f 
                f b b 2 2 b b 2 2 b b f 
                f e b d d d d d d b e f 
                . f e d d b b d d e f . 
                . f f e d d d d e f f . 
                e 4 f b 1 1 1 1 b f 4 e 
                4 d f 1 1 1 1 1 1 f d 4 
                4 4 f 6 6 6 6 6 6 f 4 4 
                . . . f f f f f f . . . 
                . . . f f . . f f . . . 
                `, SpriteKind.Enemy)
            Ka_artur.setPosition(kim.x + 10, kim.y + 10)
            Ka_artur.follow(kim, 25)
        }
    }
})
